import type { ProviderSourceInfo } from "./types";

/**
 * Registered data sources. Categories drive the badges shown in the UI:
 *   official_government → "Official Government Data"
 *   third_party         → "Third-Party Aggregated Data"
 *   demo                → "Demo Data"
 *   ai_derived          → "AI-Derived Analysis"
 */
export const SOURCES = {
  demo: {
    id: "demo",
    name: "Demo Dataset (fictional)",
    category: "demo",
    url: "https://github.com/",
    license: "Fictional sample data for demonstration only",
    description: "Bundled fictional companies, LLPs, directors, filings, financials and charges. Not real entities.",
  },
  ogd: {
    id: "ogd_datagov",
    name: "data.gov.in — RoC-wise Company Master Data (MCA)",
    category: "official_government",
    url: "https://www.data.gov.in/resource/registrars-companies-roc-wise-company-master-data",
    license: "Government Open Data License – India (GODL)",
    description:
      "Ministry of Corporate Affairs company & LLP master data published on the Open Government Data Platform. Master data only: no directors, filings, financials or charges.",
  },
  thirdParty: {
    id: "third_party_mca",
    name: "Third-party MCA data API (licensed)",
    category: "third_party",
    url: "",
    license: "Commercial licence — per provider terms",
    description: "Licensed aggregator of MCA records (directors, filings, financial statements, charges).",
  },
  aiOpenai: {
    id: "ai_openai",
    name: "AI-generated analysis (OpenAI)",
    category: "ai_derived",
    url: "https://platform.openai.com/",
    license: "Generated content — verify against cited records",
    description: "Narrative generated by an LLM strictly from cited database records.",
  },
  ruleBased: {
    id: "rule_based_analysis",
    name: "Automated rule-based analysis",
    category: "ai_derived",
    url: "",
    license: "Derived from stored records",
    description: "Deterministic calculations and templated narrative derived from stored records.",
  },
} satisfies Record<string, ProviderSourceInfo>;
